use_frameworks!

platform :ios, '9.0'

target 'MTEmptySetComponent_Example' do
  pod 'MTEmptySetComponent', :path => '../'

  target 'MTEmptySetComponent_Tests' do
    inherit! :search_paths

    
  end
end
